version: 2
updates:
  - package-ecosystem: "gomod"
    allow:
      - dependency-type: "all"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
