name: bincheck

on:
  push:
    tags: [ v* ]

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get update && sudo apt-get install -y qemu-system-x86
    - run: cd build/release/bincheck && ./test-linux v21.2.6 c7cfac57476f06e3154b2fc38e77982a8bbc64c2 ${{ github.ref_name }} ${{ github.sha }}

  darwin:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: cd build/release/bincheck && ./test-macos v21.2.6 c7cfac57476f06e3154b2fc38e77982a8bbc64c2 ${{ github.ref_name }} ${{ github.sha }}

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: cd build/release/bincheck && bash test-windows v21.2.6 c7cfac57476f06e3154b2fc38e77982a8bbc64c2 ${{ github.ref_name }} ${{ github.sha }}
